version: "3.0"
services:
  jenkins:
    image: jenkins/jenkins:lts
    user:
      - root
    ports:
      - 8080:8080
    volumes:
      - /jenkins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock

  mysql:
    image: mysql
    ports:
      - 3306:3306
    volumes:
      - /opt/lib/mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: database
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: ssafy
      MYSQL_PASSWORD: ssafy
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
