server:
  port: 8081

spring:
  profiles:
    include: secret
    active: develop
  #    active: prod
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  servlet:
    multipart:
      file-size-threshold: 1MB
      max-file-size: 100MB
      max-request-size: 100MB

---
spring:
  config:
    activate:
      on-profile: develop

  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    # test 부분을 자신이 원하는 것으로 바꾸시면 됩니다.
    username: sa # username과 password는 자신의 설정에 맞게
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create # 어플리케이션을 시작할 때 데이터베이스를 초기화하고 다시 테이블 생성
    properties:
      hibernate:
        format_sql: true # 실행되는 query를 보여줌
        show_sql: true
      logging.level:
        org.hibernate.SQL: debug

  security:
    oauth2:
      client:
        registration:
          google:
            redirect-uri: http://localhost:3000/oauth/google/callback
          kakao:
            redirect-uri: http://localhost:3000/oauth/kakao/callback

  redis:
    host: 127.0.0.1
    port: 6379